language: node_js
node_js:
  - "node"
notifications:
  email: false
sudo: false
before_install:
  - sudo apt-get install -y libhdf5-7 build-essential
before_script:
  - npm install -g grunt-cli

cache:
  directories:
    - "node_modules"
