language: node_js
node_js:
  - "node"
notifications:
  email: false
sudo: false
before_script:
  - npm install -g grunt-cli
  - sudo apt-get install -y libhdf5-7
cache:
  directories:
    - "node_modules"
